services:
  postgres:
    container_name: pytest_postgres
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - ../../../.env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -d postgres' || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 3s
    networks:
      - pytest
  app:
    container_name: pytest_app
    build:
      context: ../../../.
    env_file:
      - ../../../.env
    depends_on:
      postgres:
        condition: service_healthy
    command: /bin/sh -c 'cd /app && pytest -s -v tests'
    networks:
      - pytest
networks:
  pytest:
    driver: bridge
