services:
  test_postgres:
    container_name: test_postgres
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -d postgres' || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 3s
    networks:
      - test
  test_app:
    container_name: test_app
    build:
      context: ../.
    env_file:
      - ../.env
    depends_on:
      test_postgres:
        condition: service_healthy
    command: /bin/sh -c 'cd /app && pytest -s -v tests'
    networks:
      - test
networks:
  test:
    driver: bridge
